import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    id: uuid(),
    title: "Asus TUF Gaming GeForce GTX 1650 OC Edition 4GB GDDR6",
    inWhishlist: false,
    inCart: false,
    image:"https://www.theitdepot.com/images/proimages/33605-Asus-500.jpg",
    price: 25080,
    categoryName: "Graphic Cards",
  },
  {
    id: uuid(),
    title: "ASRock RX 6600 Challenger D 8GB Gaming Graphics Card",
    inWhishlist: false,
    inCart: false,
    image:"https://cdn.mdcomputers.in/image/cachewebp/catalog/graphics%20card/asrock/90-ga2rzz-00ianf/90-ga2rzz-00ianf-image_main-600x600.webp",
    price: 23000,
    categoryName: "Graphic Cards",
  },
  {
    id: uuid(),
    title: "Asus Dual RTX 4070 12GB Graphics Card",
    inWhishlist: false,
    inCart: false,
    image:"https://cdn.mdcomputers.in/image/cachewebp/catalog/graphics%20card/asus/dual-rtx4070-12g/dual-rtx4070-12g-image-main-600x600.webp",
    price: 61499,
    categoryName: "Graphic Cards",
  },
  {
    id: uuid(),
    title: "ANT ESPORTS ICE-C612",
    inWhishlist: false,
    inCart: false,
    image:"https://www.pcshop.in/wp-content/uploads/2020/02/ANT-ESPORTS-ICE-C612.jpg",
    price: 1225,
    categoryName: "CPU Coolers",
  },
  {
    id: uuid(),
    title: "Colorful GeForce RTX 4090 NB EX-V 24GB GDDR6X",
    inWhishlist: false,
    inCart: false,
    image:"https://m.media-amazon.com/images/I/615JOJVB6XL._SY450_.jpg",
    price: 214000,
    categoryName: "Graphic Cards",
  },
  {
    id: uuid(),
    title: "Kingston FURY Renegade 2TB PCIe Gen 4.0 NVMe Solid State Drive",
    inWhishlist: false,
    inCart: false,
    image:"https://www.theitdepot.com/images/proimages/39678_500_1.jpg",
    price: 15495,
    categoryName: "Storage",
  },
  {
    id: uuid(),
    title: "NOCTUA NH-D15 CHROMAX BLACK",
    inWhishlist: false,
    inCart: false,
    image:"https://www.pcshop.in/wp-content/uploads/2021/04/NOCTUA-NH-D15-CHROMAX-BLACK-1.png",
    price: 9100,
    categoryName: "CPU Coolers",
  },
  {
    id: uuid(),
    title: "SAMSUNG 970 EVO PLUS NVMe 250GB",
    inWhishlist: false,
    inCart: false,
    image:"https://www.pcshop.in/wp-content/uploads/2019/04/SAMSUNG-970-EVO-PLUS-NVMe-250GB.jpg",
    price: 5500,
    categoryName: "Storage",
  },
  {
    id: uuid(),
    title: "PNY 480GB CS900 INTERNAL SSD",
    inWhishlist: false,
    inCart: false,
    image:"https://www.pcshop.in/wp-content/uploads/2020/01/PNY-480GB-CS900-INTERNAL-SSD.png",
    price: 4250,
    categoryName: "Storage",
  },
  {
    id: uuid(),
    title: "Asus ROG RYUJIN III 360 ARGB AIO Liquid Cooler",
    inWhishlist: false,
    inCart: false,
    image:"https://www.theitdepot.com/images/proimages/39597_500_1.jpg",
    price: 28360,
    categoryName: "CPU Coolers",
  },
  {
    id: uuid(),
    title: "PNY 250GB CS3030 M.2 NVMe INTERNAL SSD",
    inWhishlist: false,
    inCart: false,
    image:"https://www.pcshop.in/wp-content/uploads/2020/01/PNY-250GB-CS3030-M.2-NVMe-INTERNAL-SSD.jpg",
    price: 4180,
    categoryName: "Storage",
  },
  {
    id: uuid(),
    title: "CORSAIR H55 RGB",
    inWhishlist: false,
    inCart: false,
    image:"https://www.pcshop.in/wp-content/uploads/2021/08/CORSAIR-H55-RGB.png",
    price: 5800,
    categoryName: "CPU Coolers",
  },
  {
    id: uuid(),
    title: "Asus Dual RTX 3050 OC LHR 8GB Gaming Graphics Card",
    inWhishlist: false,
    inCart: false,
    image:"https://cdn.mdcomputers.in/image/cachewebp/catalog/graphics%20card/asus_new/dual-rtx3050-o8g/asus-dual-rtx3050-o8g-image-main-600x600.webp",
    price: 27599,
    categoryName: "Graphic Cards",
  },
];
